### ISSUE TITLE
ここペディア

### ISSUE THREAD

**Issue by midoriit** [fumi/dbpedia-japanese-usecases#1]
「ここペディア」のAndroidアプリ配布は終了し、現在は以下のURLでWebアプリになっています。
http://kokopedia.midoriit.com/
ソースコードはこちらです。
https://github.com/midoriit/kokopedia
宜しくお願いします。

**Comment by fumi** [comment]
ありがとうございます．反映させました．

https://github.com/fumi/dbpedia-japanese-usecases/commit/b658475371cee38dbbd3f46919eadc26963b2854
